### ISSUE TITLE
RSI with 3 months of data?

### ISSUE THREAD

**Issue by chrisabrams** [andredumas/techan.js#131]
I'm feeding the RSI with 3 months of data, but it's only graphing the last two months. How do I make the RSI handle 3 months? I looked at the rsi plot code and I don't see anything limiting the months there.

**Comment by andredumas** [comment]
Most indicators with a period need to be primed before they start emitting anything useful. That's probably what you're seeing. ie rsi needs 14 [periods](https://github.com/andredumas/techan.js/blob/master/src/indicator/rsi.js#L23) of moving average otherwise the calculation won't be very helpful.

If you want 3 complete months of rsi, you will need 3 months + rsi period of data.
