### ISSUE TITLE
how to use refreshIndicator for ichimoku? 

### ISSUE THREAD

**Issue by DielOliveira** [andredumas/techan.js#143]
I need to 'feed' an ichimoku chart, but I do not know how to refresh the indicator in real time. Someone know? 

I tried to use refreshIndicator, but  I could not make it works.

Thank you!

**Comment by andredumas** [comment]
Will be updating examples which will demonstrate how data can be refreshed for all plots. Keep an eye on #49, should be completed soon. This will require an update to the latest 0.7.0-dev build though when pushed.

In the meantime have a look at the [feeds](http://bl.ocks.org/andredumas/95f1f22130fb1a3a8181) example. In short you need to mutate the ichimoku/indicator array in place rather than a full refresh for the plot to correctly pick this up. #49 will remove the need for this.
