### ISSUE TITLE
<path> attribute d: Expected number, "...7.13131,NaN l 38.31212..."

### ISSUE THREAD

**Issue by icastillejogomez** [andredumas/techan.js#237]
My chart works well but when the candles are few I got this error:
```
Error: <path> attribute d: Expected number, "…7.3255813953497 NaN l 38.3720930…".
```

I tested all posible things but I'm really sure that the chart logic is correct because in all other cases when the chart has a relevant number of candles works out.

**Comment by icastillejogomez** [comment]
If I set 33 candles or less crash, otherwise works out!

Please help!! 😢 

@andredumas

**Comment by icastillejogomez** [comment]
Okay. In "All plots" example `indicatorPreRoll` variable is setting to 33. This is the key, but... exactly what is `indicatorPreRoll`?

**Comment by briancappello** [comment]
Check for invalid input data and or division by zero? Whenever I've come
across the expected number errors that's been the problem

Indicator pre roll, also called lookback, is the number of price bars that
should be skipped before the respective indicator values are to be
considered valid. Or, alternatively, if you wanted to display 100 bars of
valid data you would need 100+33 (the lookback) price bars in order to have
100 "complete" bars

**Comment by icastillejogomez** [comment]
Thank you so mucho @briancappello you are the best!! :+1:
