### ISSUE TITLE
is this project dead?

### ISSUE THREAD

**Issue by 34r7h** [andredumas/techan.js#248]

**Comment by briancappello** [comment]
The code still works, but it's been over 3 years since the latest commit (or for that matter, any word at all from @andredumas). There are a few minor bugs in various corners that you may or may not come across depending on your needs. But if you do encounter any, you'll probably need to fix them yourself. That, and the code is ES5 and integrating it with "modern" build tools and/or JS frameworks is not always super straight forward.

If you're using React, https://github.com/rrag/react-stockcharts is an alternative

**Comment by trasherdk** [comment]
While the code base is sound, and in a working state. There has been no progress, or response for a while.
I'm using this for some basic graphing, but without low level documentation, it's kinda hard to evolve.
I would wish for someone smarter than me to pick up this project, and carry it forward.

**Comment by 34r7h** [comment]
thanks for the info @trasherdk  and @briancappello. This is a cool lib but difficult to reason about without docs. The https://d3fc.io/ project is pretty cool, not as featured tho.
