### ISSUE TITLE
Candlestick width, setting max width

### ISSUE THREAD

**Issue by prionkor** [andredumas/techan.js#51]
How can I set maximum width for candlesticks? Currently if the amount of data is very few the sticks becomes very fat.

JSfiddle example: http://jsfiddle.net/Lfdyrvm3/

**Comment by andredumas** [comment]
I've never needed to plot so few candlesticks other than zooming up to examine detail. And seeing wide candles has never been a problem. Is plotting so few candles something you frequently do? Would this also include volume and other plot width?

As a workaround I've made a slight mod (line 12) to your example to adjust the width. This will affect everything that uses x.band() to determine width: volume, macd, etc.

http://jsfiddle.net/Lfdyrvm3/1/

**Comment by prionkor** [comment]
> Is plotting so few candles something you frequently do?

Not really. But was curious what I can do when there is low number of sticks on a chart. Thanks for your help by the way. 

Is there any way I bring those sticks closer?

Off topic: I will be working closely with charts next couple of months. I hope I can start doing some contribution on this exciting repo. If not with code I will do some wiki.

**Comment by andredumas** [comment]
To bring the sticks closer, it sounds like rather than set max candle width, might be better just zooming out a little. It will give you both: closer grouping and thinner candles. It's what I first thought looking at the example after I applied a set thin candle width.

Updated example http://jsfiddle.net/Lfdyrvm3/3/
See line 74

**Comment by prionkor** [comment]
Thanks! I got the idea..
