### ISSUE TITLE
Adding New Candle Sticks

### ISSUE THREAD

**Issue by prionkor** [andredumas/techan.js#81]
Would like to know how do I add new candle sticks to an already existing chart. For example when I click a button There will be 6 new sticks on the chart. If previously was 30 then it will be 36 now. Similarly how to remove sticks.

No documentation on library so do not have a clue.

**Comment by andredumas** [comment]
Hi @prionkor 

This is more or less standard d3. As long as you update the underlying data structure that has been bound to the DOM node, when you redraw the candlestick, it will redraw based on the data. Refer to the feed example:
1. [Updating the underlying data](https://gist.github.com/andredumas/95f1f22130fb1a3a8181#file-index-html-L256) [already bound to the DOM](https://gist.github.com/andredumas/95f1f22130fb1a3a8181#file-index-html-L212). Obviously your logic for clicks needs to be around here instead of timeout.
2. [Redraw the candlestick](https://gist.github.com/andredumas/95f1f22130fb1a3a8181#file-index-html-L243)

andre
